Improve install script.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,7 +7,7 @@ config_backup_dir="backup-$(date +%F-%H-%M-%S)";
 
 install_file() {
 	if [[ -e "$HOME/$2" || -L "$HOME/$2" ]]; then
-		if [ "$(readlink "$HOME/$2")" != "$1" ]; then
+		if [[ "$(readlink "$HOME/$2")" != "$1" ]]; then
 			mkdir -p  "$(dirname "$config_backup_dir/$2")"
 			mv "$HOME/$2" "$config_backup_dir/$2"
 			echo "'$2' already exists. It is moved to '$config_dir/$config_backup_dir/$2'." 1>&2
@@ -20,8 +20,7 @@ install_file() {
 
 install_config_dir_symlink() {
 	if [[ -e "$HOME/.config/$1" || -L "$HOME/.config/$1" ]]; then
-		readlink "$HOME/.config/$1"
-		if [ "$(readlink "$HOME/.config/$1")" != "../$config_dir/config/$1" ]; then
+		if [[ "$(readlink "$HOME/.config/$1")" != "../$config_dir/config/$1" ]]; then
 			mkdir -p "$config_backup_dir"
 			mv "$HOME/.config/$1" "$config_backup_dir/$1"
 			echo "'$1' already exists. It is moved to '$config_dir/$config_backup_dir/$1'." 1>&2
@@ -44,11 +43,14 @@ for dir in hypr waybar dunst gtk-3.0; do
 	install_config_dir_symlink "$dir"
 done
 
+if ! command -v Hyprland > /dev/null; then
+	echo 'Missing command: Hyprland'
+fi
 
 if ! command -v dunst > /dev/null; then
-	echo "Did not find `dunst` in PATH"
+	echo 'Missing command: dunst'
 fi
 
 if ! command -v waybar > /dev/null; then
-	echo "Did not find `waybar` in PATH"
+	echo 'Missing command: waybar'
 fi
